<?php
return [
    ["CodePays" => "AD", "LibellePays" => "Andorre", "Nationalite" => "Andorrane"],
    ["CodePays" => "AE", "LibellePays" => "Émirats arabes unis", "Nationalite" => "Emirienne"],
    ["CodePays" => "AF", "LibellePays" => "Afghanistan", "Nationalite" => "Afghane"],
    ["CodePays" => "AG", "LibellePays" => "Antigua-et-Barbuda", "Nationalite" => "Antiguaise et barbudienne"],
    ["CodePays" => "AI", "LibellePays" => "Anguilla", "Nationalite" => "-"],
    ["CodePays" => "AL", "LibellePays" => "Albanie", "Nationalite" => "Albanaise"],
    ["CodePays" => "AM", "LibellePays" => "Arménie", "Nationalite" => "Arménienne"],
    ["CodePays" => "AO", "LibellePays" => "Angola", "Nationalite" => "Angolaise"],
    ["CodePays" => "AQ", "LibellePays" => "Antarctique", "Nationalite" => "-"],
    ["CodePays" => "AR", "LibellePays" => "Argentine", "Nationalite" => "Argentine"],
    ["CodePays" => "AS", "LibellePays" => "Samoa américaines", "Nationalite" => "-"],
    ["CodePays" => "AT", "LibellePays" => "Autriche", "Nationalite" => "Autrichienne"],
    ["CodePays" => "AU", "LibellePays" => "Australie", "Nationalite" => "Australienne"],
    ["CodePays" => "AW", "LibellePays" => "Aruba", "Nationalite" => "-"],
    ["CodePays" => "AX", "LibellePays" => "Åland (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "AZ", "LibellePays" => "Azerbaïdjan", "Nationalite" => "Azerbaïdjanaise"],
    ["CodePays" => "BA", "LibellePays" => "Bosnie-Herzégovine", "Nationalite" => "Bosnienne"],
    ["CodePays" => "BB", "LibellePays" => "Barbade", "Nationalite" => "Barbadienne"],
    ["CodePays" => "BD", "LibellePays" => "Bangladesh", "Nationalite" => "Bangladaise"],
    ["CodePays" => "BE", "LibellePays" => "Belgique", "Nationalite" => "Belge"],
    ["CodePays" => "BF", "LibellePays" => "Burkina Faso", "Nationalite" => "Burkinabé"],
    ["CodePays" => "BG", "LibellePays" => "Bulgarie", "Nationalite" => "Bulgare"],
    ["CodePays" => "BH", "LibellePays" => "Bahreïn", "Nationalite" => "Bahreinienne"],
    ["CodePays" => "BI", "LibellePays" => "Burundi", "Nationalite" => "Burundaise"],
    ["CodePays" => "BJ", "LibellePays" => "Bénin", "Nationalite" => "Béninoise"],
    ["CodePays" => "BL", "LibellePays" => "Saint-Barthélemy", "Nationalite" => "-"],
    ["CodePays" => "BM", "LibellePays" => "Bermudes", "Nationalite" => "-"],
    ["CodePays" => "BN", "LibellePays" => "Brunéi Darussalam", "Nationalite" => "Bruneienne"],
    ["CodePays" => "BO", "LibellePays" => "Bolivie (État plurinational de)", "Nationalite" => "Bolivienne"],
    ["CodePays" => "BQ", "LibellePays" => "Bonaire, Saint-Eustache et Saba", "Nationalite" => "-"],
    ["CodePays" => "BR", "LibellePays" => "Brésil", "Nationalite" => "Brésilienne"],
    ["CodePays" => "BS", "LibellePays" => "Bahamas", "Nationalite" => "Bahamienne"],
    ["CodePays" => "BT", "LibellePays" => "Bhoutan", "Nationalite" => "Bhoutanaise"],
    ["CodePays" => "BV", "LibellePays" => "Bouvet (l'Île)", "Nationalite" => "-"],
    ["CodePays" => "BW", "LibellePays" => "Botswana", "Nationalite" => "Botswanaise"],
    ["CodePays" => "BY", "LibellePays" => "Bélarus", "Nationalite" => "Biélorusse"],
    ["CodePays" => "BZ", "LibellePays" => "Belize", "Nationalite" => "Bélizienne"],
    ["CodePays" => "CA", "LibellePays" => "Canada", "Nationalite" => "Canadienne"],
    ["CodePays" => "CC", "LibellePays" => "Cocos (les Îles) / Keeling (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "CD", "LibellePays" => "Congo (la République démocratique du)", "Nationalite" => "Congolaise (Kinshasa)"],
    ["CodePays" => "CF", "LibellePays" => "République centrafricaine", "Nationalite" => "Centrafricaine"],
    ["CodePays" => "CG", "LibellePays" => "Congo", "Nationalite" => "Congolaise"],
    ["CodePays" => "CH", "LibellePays" => "Suisse", "Nationalite" => "Suisse"],
    ["CodePays" => "CI", "LibellePays" => "Côte d'Ivoire", "Nationalite" => "Ivoirienne"],
    ["CodePays" => "CK", "LibellePays" => "Cook (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "CL", "LibellePays" => "Chili", "Nationalite" => "Chilienne"],
    ["CodePays" => "CM", "LibellePays" => "Cameroun", "Nationalite" => "Camerounaise"],
    ["CodePays" => "CN", "LibellePays" => "Chine", "Nationalite" => "Chinoise"],
    ["CodePays" => "CO", "LibellePays" => "Colombie", "Nationalite" => "Colombienne"],
    ["CodePays" => "CR", "LibellePays" => "Costa Rica", "Nationalite" => "Costaricaine"],
    ["CodePays" => "CU", "LibellePays" => "Cuba", "Nationalite" => "Cubaine"],
    ["CodePays" => "CV", "LibellePays" => "Cabo Verde", "Nationalite" => "Cap-verdienne"],
    ["CodePays" => "CW", "LibellePays" => "Curaçao", "Nationalite" => "-"],
    ["CodePays" => "CX", "LibellePays" => "Christmas (l'Île)", "Nationalite" => "-"],
    ["CodePays" => "CY", "LibellePays" => "Chypre", "Nationalite" => "Chypriote"],
    ["CodePays" => "CZ", "LibellePays" => "Tchéquie", "Nationalite" => "Tchèque"],
    ["CodePays" => "DE", "LibellePays" => "Allemagne", "Nationalite" => "Allemande"],
    ["CodePays" => "DJ", "LibellePays" => "Djibouti", "Nationalite" => "Djiboutienne"],
    ["CodePays" => "DK", "LibellePays" => "Danemark", "Nationalite" => "Danoise"],
    ["CodePays" => "DM", "LibellePays" => "Dominique", "Nationalite" => "Dominiquaise"],
    ["CodePays" => "DO", "LibellePays" => "Dominicaine (la République)", "Nationalite" => "Dominicaine"],
    ["CodePays" => "DZ", "LibellePays" => "Algérie", "Nationalite" => "Algérienne"],
    ["CodePays" => "EC", "LibellePays" => "Équateur", "Nationalite" => "Equatorienne"],
    ["CodePays" => "EE", "LibellePays" => "Estonie", "Nationalite" => "Estonienne"],
    ["CodePays" => "EG", "LibellePays" => "Égypte", "Nationalite" => "Egyptienne"],
    ["CodePays" => "EH", "LibellePays" => "Sahara occidental", "Nationalite" => "-"],
    ["CodePays" => "ER", "LibellePays" => "Érythrée", "Nationalite" => "Erythréenne"],
    ["CodePays" => "ES", "LibellePays" => "Espagne", "Nationalite" => "Espagnole"],
    ["CodePays" => "ET", "LibellePays" => "Éthiopie", "Nationalite" => "Ethiopienne"],
    ["CodePays" => "FI", "LibellePays" => "Finlande", "Nationalite" => "Finlandaise"],
    ["CodePays" => "FJ", "LibellePays" => "Fidji", "Nationalite" => "Fidjienne"],
    ["CodePays" => "FK", "LibellePays" => "Falkland (les Îles) /Malouines (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "FM", "LibellePays" => "Micronésie (États fédérés de)", "Nationalite" => "Micronésienne"],
    ["CodePays" => "FO", "LibellePays" => "Féroé (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "FR", "LibellePays" => "France", "Nationalite" => "Française"],
    ["CodePays" => "GA", "LibellePays" => "Gabon", "Nationalite" => "Gabonaise"],
    ["CodePays" => "GB", "LibellePays" => "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", "Nationalite" => "Britannique (RU)"],
    ["CodePays" => "GD", "LibellePays" => "Grenade", "Nationalite" => "Grenadienne"],
    ["CodePays" => "GE", "LibellePays" => "Géorgie", "Nationalite" => "Georgienne"],
    ["CodePays" => "GF", "LibellePays" => "Guyane française (la)", "Nationalite" => "Guyanienne"],
    ["CodePays" => "GG", "LibellePays" => "Guernesey", "Nationalite" => "-"],
    ["CodePays" => "GH", "LibellePays" => "Ghana", "Nationalite" => "Ghanéenne"],
    ["CodePays" => "GI", "LibellePays" => "Gibraltar", "Nationalite" => "-"],
    ["CodePays" => "GL", "LibellePays" => "Groenland", "Nationalite" => "-"],
    ["CodePays" => "GM", "LibellePays" => "Gambie", "Nationalite" => "Gambienne"],
    ["CodePays" => "GN", "LibellePays" => "Guinée", "Nationalite" => "Guinéenne"],
    ["CodePays" => "GP", "LibellePays" => "Guadeloupe", "Nationalite" => "-"],
    ["CodePays" => "GQ", "LibellePays" => "Guinée équatoriale", "Nationalite" => "Equato-guinéenne"],
    ["CodePays" => "GR", "LibellePays" => "Grèce", "Nationalite" => "Hellénique"],
    ["CodePays" => "GS", "LibellePays" => "Géorgie du Sud-et-les Îles Sandwich du Sud", "Nationalite" => "-"],
    ["CodePays" => "GT", "LibellePays" => "Guatemala", "Nationalite" => "Guatemaltèque"],
    ["CodePays" => "GU", "LibellePays" => "Guam", "Nationalite" => "-"],
    ["CodePays" => "GW", "LibellePays" => "Guinée-Bissau", "Nationalite" => "Bissau-Guinéenne"],
    ["CodePays" => "GY", "LibellePays" => "Guyana", "Nationalite" => "Guyanaise (Guyana)"],
    ["CodePays" => "HK", "LibellePays" => "Hong Kong", "Nationalite" => "-"],
    ["CodePays" => "HM", "LibellePays" => "Heard-et-Îles MacDonald (l'Île)", "Nationalite" => "-"],
    ["CodePays" => "HN", "LibellePays" => "Honduras", "Nationalite" => "Hondurienne"],
    ["CodePays" => "HR", "LibellePays" => "Croatie", "Nationalite" => "Croate"],
    ["CodePays" => "HT", "LibellePays" => "Haïti", "Nationalite" => "Haïtienne"],
    ["CodePays" => "HU", "LibellePays" => "Hongrie", "Nationalite" => "Hongroise"],
    ["CodePays" => "ID", "LibellePays" => "Indonésie", "Nationalite" => "Indonésienne"],
    ["CodePays" => "IE", "LibellePays" => "Irlande", "Nationalite" => "Irlandaise"],
    ["CodePays" => "IL", "LibellePays" => "Israël", "Nationalite" => "Israélienne"],
    ["CodePays" => "IM", "LibellePays" => "Île de Man", "Nationalite" => "-"],
    ["CodePays" => "IN", "LibellePays" => "Inde", "Nationalite" => "Indienne"],
    ["CodePays" => "IO", "LibellePays" => "Indien (le Territoire britannique de l'océan)", "Nationalite" => "-"],
    ["CodePays" => "IQ", "LibellePays" => "Iraq", "Nationalite" => "Irakienne"],
    ["CodePays" => "IR", "LibellePays" => "Iran (République Islamique d')", "Nationalite" => "Iranienne"],
    ["CodePays" => "IS", "LibellePays" => "Islande", "Nationalite" => "Islandaise"],
    ["CodePays" => "IT", "LibellePays" => "Italie", "Nationalite" => "Italienne"],
    ["CodePays" => "JE", "LibellePays" => "Jersey", "Nationalite" => "-"],
    ["CodePays" => "JM", "LibellePays" => "Jamaïque", "Nationalite" => "Jamaïcaine"],
    ["CodePays" => "JO", "LibellePays" => "Jordanie", "Nationalite" => "Jordanienne"],
    ["CodePays" => "JP", "LibellePays" => "Japon", "Nationalite" => "Japonaise"],
    ["CodePays" => "KE", "LibellePays" => "Kenya", "Nationalite" => "Kenyane"],
    ["CodePays" => "KG", "LibellePays" => "Kirghizistan", "Nationalite" => "Kirghize"],
    ["CodePays" => "KH", "LibellePays" => "Cambodge", "Nationalite" => "Cambodgienne"],
    ["CodePays" => "KI", "LibellePays" => "Kiribati", "Nationalite" => "Kiribatienne"],
    ["CodePays" => "KM", "LibellePays" => "Comores", "Nationalite" => "Comorienne"],
    ["CodePays" => "KN", "LibellePays" => "Saint-Kitts-et-Nevis", "Nationalite" => "Kittitienne-et-névicienne"],
    ["CodePays" => "KP", "LibellePays" => "Corée (la République populaire démocratique de)", "Nationalite" => "Nord-coréenne"],
    ["CodePays" => "KR", "LibellePays" => "Corée (la République de)", "Nationalite" => "Sud-coréenne"],
    ["CodePays" => "KW", "LibellePays" => "Koweït", "Nationalite" => "Koweitienne"],
    ["CodePays" => "KY", "LibellePays" => "Caïmans (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "KZ", "LibellePays" => "Kazakhstan", "Nationalite" => "Kazakhstanaise"],
    ["CodePays" => "LA", "LibellePays" => "Lao (la République démocratique populaire)", "Nationalite" => "Laotienne"],
    ["CodePays" => "LB", "LibellePays" => "Liban", "Nationalite" => "Libanaise"],
    ["CodePays" => "LC", "LibellePays" => "Sainte-Lucie", "Nationalite" => "Saint-Lucienne"],
    ["CodePays" => "LI", "LibellePays" => "Liechtenstein", "Nationalite" => "Liechtensteinoise"],
    ["CodePays" => "LK", "LibellePays" => "Sri Lanka", "Nationalite" => "Sri-lankaise"],
    ["CodePays" => "LR", "LibellePays" => "Libéria", "Nationalite" => "Libérienne"],
    ["CodePays" => "LS", "LibellePays" => "Lesotho", "Nationalite" => "Lesothane"],
    ["CodePays" => "LT", "LibellePays" => "Lituanie", "Nationalite" => "Lituanienne"],
    ["CodePays" => "LU", "LibellePays" => "Luxembourg", "Nationalite" => "Luxembourgeoise"],
    ["CodePays" => "LV", "LibellePays" => "Lettonie", "Nationalite" => "Lettone"],
    ["CodePays" => "LY", "LibellePays" => "Libye", "Nationalite" => "Libyenne"],
    ["CodePays" => "MA", "LibellePays" => "Maroc", "Nationalite" => "Marocaine"],
    ["CodePays" => "MC", "LibellePays" => "Monaco", "Nationalite" => "Monégasque"],
    ["CodePays" => "MD", "LibellePays" => "Moldavie (la République de)", "Nationalite" => "Moldave"],
    ["CodePays" => "ME", "LibellePays" => "Monténégro", "Nationalite" => "Monténégrine"],
    ["CodePays" => "MF", "LibellePays" => "Saint-Martin (partie française)", "Nationalite" => "-"],
    ["CodePays" => "MG", "LibellePays" => "Madagascar", "Nationalite" => "Malgache"],
    ["CodePays" => "MH", "LibellePays" => "Marshall (les Îles)", "Nationalite" => "Marshallaise"],
    ["CodePays" => "MK", "LibellePays" => "Macédoine du Nord", "Nationalite" => "Macédonienne"],
    ["CodePays" => "ML", "LibellePays" => "Mali", "Nationalite" => "Malienne"],
    ["CodePays" => "MM", "LibellePays" => "Myanmar", "Nationalite" => "Birmane"],
    ["CodePays" => "MN", "LibellePays" => "Mongolie", "Nationalite" => "Mongole"],
    ["CodePays" => "MO", "LibellePays" => "Macao", "Nationalite" => "-"],
    ["CodePays" => "MP", "LibellePays" => "Mariannes du Nord (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "MQ", "LibellePays" => "Martinique", "Nationalite" => "-"],
    ["CodePays" => "MR", "LibellePays" => "Mauritanie", "Nationalite" => "Mauritanienne"],
    ["CodePays" => "MS", "LibellePays" => "Montserrat", "Nationalite" => "-"],
    ["CodePays" => "MT", "LibellePays" => "Malte", "Nationalite" => "Maltaise"],
    ["CodePays" => "MU", "LibellePays" => "Maurice", "Nationalite" => "Mauricienne"],
    ["CodePays" => "MV", "LibellePays" => "Maldives", "Nationalite" => "Maldivienne"],
    ["CodePays" => "MW", "LibellePays" => "Malawi", "Nationalite" => "Malawienne"],
    ["CodePays" => "MX", "LibellePays" => "Mexique", "Nationalite" => "Mexicaine"],
    ["CodePays" => "MY", "LibellePays" => "Malaisie", "Nationalite" => "Malaisienne"],
    ["CodePays" => "MZ", "LibellePays" => "Mozambique", "Nationalite" => "Mozambicaine"],
    ["CodePays" => "NA", "LibellePays" => "Namibie", "Nationalite" => "Namibienne"],
    ["CodePays" => "NC", "LibellePays" => "Nouvelle-Calédonie", "Nationalite" => "-"],
    ["CodePays" => "NE", "LibellePays" => "Niger", "Nationalite" => "Nigérienne"],
    ["CodePays" => "NF", "LibellePays" => "Norfolk (l'Île)", "Nationalite" => "-"],
    ["CodePays" => "NG", "LibellePays" => "Nigéria", "Nationalite" => "Nigériane"],
    ["CodePays" => "NI", "LibellePays" => "Nicaragua", "Nationalite" => "Nicaraguayenne"],
    ["CodePays" => "NL", "LibellePays" => "Pays-Bas", "Nationalite" => "Néerlandaise"],
    ["CodePays" => "NO", "LibellePays" => "Norvège", "Nationalite" => "Norvégienne"],
    ["CodePays" => "NP", "LibellePays" => "Népal", "Nationalite" => "Népalaise"],
    ["CodePays" => "NR", "LibellePays" => "Nauru", "Nationalite" => "Nauruane"],
    ["CodePays" => "NU", "LibellePays" => "Niue", "Nationalite" => "-"],
    ["CodePays" => "NZ", "LibellePays" => "Nouvelle-Zélande", "Nationalite" => "Neo-zélandaise"],
    ["CodePays" => "OM", "LibellePays" => "Oman", "Nationalite" => "Omanaise"],
    ["CodePays" => "PA", "LibellePays" => "Panama", "Nationalite" => "Panaméenne"],
    ["CodePays" => "PE", "LibellePays" => "Pérou", "Nationalite" => "Péruvienne"],
    ["CodePays" => "PF", "LibellePays" => "Polynésie française", "Nationalite" => "-"],
    ["CodePays" => "PG", "LibellePays" => "Papouasie-Nouvelle-Guinée", "Nationalite" => "Papouane-neoguinéenne"],
    ["CodePays" => "PH", "LibellePays" => "Philippines", "Nationalite" => "Philippine"],
    ["CodePays" => "PK", "LibellePays" => "Pakistan", "Nationalite" => "Pakistanaise"],
    ["CodePays" => "PL", "LibellePays" => "Pologne", "Nationalite" => "Polonaise"],
    ["CodePays" => "PM", "LibellePays" => "Saint-Pierre-et-Miquelon", "Nationalite" => "-"],
    ["CodePays" => "PN", "LibellePays" => "Pitcairn", "Nationalite" => "-"],
    ["CodePays" => "PR", "LibellePays" => "Porto Rico", "Nationalite" => "Portoricaine"],
    ["CodePays" => "PS", "LibellePays" => "Palestine, État de", "Nationalite" => "Palestinienne"],
    ["CodePays" => "PT", "LibellePays" => "Portugal", "Nationalite" => "Portugaise"],
    ["CodePays" => "PW", "LibellePays" => "Palaos", "Nationalite" => "Palau"],
    ["CodePays" => "PY", "LibellePays" => "Paraguay", "Nationalite" => "Paraguayenne"],
    ["CodePays" => "QA", "LibellePays" => "Qatar", "Nationalite" => "Qatarienne"],
    ["CodePays" => "RE", "LibellePays" => "Réunion", "Nationalite" => "-"],
    ["CodePays" => "RO", "LibellePays" => "Roumanie", "Nationalite" => "Roumaine"],
    ["CodePays" => "RS", "LibellePays" => "Serbie", "Nationalite" => "Serbe"],
    ["CodePays" => "RU", "LibellePays" => "Russie (la Fédération de)", "Nationalite" => "Russe"],
    ["CodePays" => "RW", "LibellePays" => "Rwanda", "Nationalite" => "Rwandaise"],
    ["CodePays" => "SA", "LibellePays" => "Arabie saoudite", "Nationalite" => "Saoudienne"],
    ["CodePays" => "SB", "LibellePays" => "Salomon (les Îles)", "Nationalite" => "Salomonaise"],
    ["CodePays" => "SC", "LibellePays" => "Seychelles", "Nationalite" => "Seychelloise"],
    ["CodePays" => "SD", "LibellePays" => "Soudan", "Nationalite" => "Soudanaise"],
    ["CodePays" => "SE", "LibellePays" => "Suède", "Nationalite" => "Suédoise"],
    ["CodePays" => "SG", "LibellePays" => "Singapour", "Nationalite" => "Singapourienne"],
    ["CodePays" => "SH", "LibellePays" => "Sainte-Hélène, Ascension et Tristan da Cunha", "Nationalite" => "-"],
    ["CodePays" => "SI", "LibellePays" => "Slovénie", "Nationalite" => "Slovène"],
    ["CodePays" => "SJ", "LibellePays" => "Svalbard et l'Île Jan Mayen", "Nationalite" => "-"],
    ["CodePays" => "SK", "LibellePays" => "Slovaquie", "Nationalite" => "Slovaque"],
    ["CodePays" => "SL", "LibellePays" => "Sierra Leone", "Nationalite" => "Sierra-leonaise"],
    ["CodePays" => "SM", "LibellePays" => "Saint-Marin", "Nationalite" => "Saint-Marinaise"],
    ["CodePays" => "SN", "LibellePays" => "Sénégal", "Nationalite" => "Sénégalaise"],
    ["CodePays" => "SO", "LibellePays" => "Somalie", "Nationalite" => "Somalienne"],
    ["CodePays" => "SR", "LibellePays" => "Suriname", "Nationalite" => "Surinamaise"],
    ["CodePays" => "SS", "LibellePays" => "Soudan du Sud", "Nationalite" => "Sud soudanaise"],
    ["CodePays" => "ST", "LibellePays" => "Sao Tomé-et-Principe", "Nationalite" => "Santoméenne"],
    ["CodePays" => "SV", "LibellePays" => "El Salvador", "Nationalite" => "Salvadorienne"],
    ["CodePays" => "SX", "LibellePays" => "Saint-Martin (partie néerlandaise)", "Nationalite" => "-"],
    ["CodePays" => "SY", "LibellePays" => "République arabe syrienne", "Nationalite" => "Syrienne"],
    ["CodePays" => "SZ", "LibellePays" => "Eswatini", "Nationalite" => ""],
    ["CodePays" => "TC", "LibellePays" => "Turks-et-Caïcos (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "TD", "LibellePays" => "Tchad", "Nationalite" => "Tchadienne"],
    ["CodePays" => "TF", "LibellePays" => "Terres australes françaises", "Nationalite" => "-"],
    ["CodePays" => "TG", "LibellePays" => "Togo", "Nationalite" => "Togolaise"],
    ["CodePays" => "TH", "LibellePays" => "Thaïlande", "Nationalite" => "Thaïlandaise"],
    ["CodePays" => "TJ", "LibellePays" => "Tadjikistan", "Nationalite" => "Tadjike"],
    ["CodePays" => "TK", "LibellePays" => "Tokelau", "Nationalite" => "-"],
    ["CodePays" => "TL", "LibellePays" => "Timor-Leste", "Nationalite" => "Est-timoraise"],
    ["CodePays" => "TM", "LibellePays" => "Turkménistan", "Nationalite" => "Turkmène"],
    ["CodePays" => "TN", "LibellePays" => "Tunisie", "Nationalite" => "Tunisienne"],
    ["CodePays" => "TO", "LibellePays" => "Tonga", "Nationalite" => "Tongienne"],
    ["CodePays" => "TR", "LibellePays" => "Turquie", "Nationalite" => "Turque"],
    ["CodePays" => "TT", "LibellePays" => "Trinité-et-Tobago", "Nationalite" => "Trinidadienne"],
    ["CodePays" => "TV", "LibellePays" => "Tuvalu", "Nationalite" => "Tuvaluane"],
    ["CodePays" => "TW", "LibellePays" => "Taïwan (Province de Chine)", "Nationalite" => "Taiwanaise"],
    ["CodePays" => "TZ", "LibellePays" => "Tanzanie (la République-Unie de)", "Nationalite" => "Tanzanienne"],
    ["CodePays" => "UA", "LibellePays" => "Ukraine", "Nationalite" => "Ukrainienne"],
    ["CodePays" => "UG", "LibellePays" => "Ouganda", "Nationalite" => "Ougandaise"],
    ["CodePays" => "UM", "LibellePays" => "Îles mineures éloignées des États-Unis", "Nationalite" => "-"],
    ["CodePays" => "US", "LibellePays" => "États-Unis d'Amérique", "Nationalite" => "Américaine"],
    ["CodePays" => "UY", "LibellePays" => "Uruguay", "Nationalite" => "Uruguayenne"],
    ["CodePays" => "UZ", "LibellePays" => "Ouzbékistan", "Nationalite" => "Ouzbeke"],
    ["CodePays" => "VA", "LibellePays" => "Saint-Siège", "Nationalite" => ""],
    ["CodePays" => "VC", "LibellePays" => "Saint-Vincent-et-les Grenadines", "Nationalite" => "Saint-Vincentaise-et-Grenadine"],
    ["CodePays" => "VE", "LibellePays" => "Venezuela (République bolivarienne du)", "Nationalite" => "Vénézuélienne"],
    ["CodePays" => "VG", "LibellePays" => "Vierges britanniques (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "VI", "LibellePays" => "Vierges des États-Unis (les Îles)", "Nationalite" => "-"],
    ["CodePays" => "VN", "LibellePays" => "Viet Nam", "Nationalite" => "Vietnamienne"],
    ["CodePays" => "VU", "LibellePays" => "Vanuatu", "Nationalite" => "Vanuatuane"],
    ["CodePays" => "WF", "LibellePays" => "Wallis-et-Futuna", "Nationalite" => "-"],
    ["CodePays" => "WS", "LibellePays" => "Samoa", "Nationalite" => "Samoane"],
    ["CodePays" => "YE", "LibellePays" => "Yémen", "Nationalite" => "Yéménite"],
    ["CodePays" => "YT", "LibellePays" => "Mayotte", "Nationalite" => "-"],
    ["CodePays" => "ZA", "LibellePays" => "Afrique du Sud", "Nationalite" => "Sud-africaine"],
    ["CodePays" => "ZM", "LibellePays" => "Zambie", "Nationalite" => "Zambienne"],
    ["CodePays" => "ZW", "LibellePays" => "Zimbabwe", "Nationalite" => "Zimbabwéenne"]
];
